version: '3.9'

services:
  traefik:
    image: 'traefik:${TRAEFIK_IMAGE_VERSION:-v2.10}'
    command:
      # Provider
      - '--providers.docker'
      - '--providers.docker.exposedbydefault=${TRAEFIK_EXPOSED_BY_DEFAULT:-false}'
      - '--providers.docker.network=my-server_server'
      # Entrypoints
      - '--entrypoints.web.address=:${TRAEFIK_WEB_ENTRYPOINT:-80}'
      - '--entrypoints.websecure.address=:${TRAEFIK_WEBSECURE_ENTRYPOINT:-443}'
      - '--entrypoints.web.http.redirections.entrypoint.to=websecure'
      # Let's Encrypt
      # - '--certificatesresolvers.myresolver.acme.email=${ROOT_EMAIL:-changeme@changeme.org}'
      # - '--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web'
      # - '--certificatesresolvers.myresolver.acme.httpchallenge=true'
      - '--entrypoints.websecure.http.tls.certresolver=myresolver'
      # HTTP/3
      - '--experimental.http3=true'
      - '--entrypoints.websecure.http3'
      # Logs
      - '--accesslog.filepath=/logs/access.log'
      - '--accesslog.format=json'
      - '--log.filepath=/logs/traefik.log'
      - '--log.format=json'
      - '--log.level=${TRAEFIK_LOG_LEVEL:-ERROR}'
      # Misc
      - '--api.dashboard'
      # - '--entrypoints.websecure.http.middlewares=compress@file,headers@file${TRAEFIK_PLUGINS:-}'
      - '--global.checknewversion=${TRAEFIK_CHECK_NEW_VERSION:-false}'
      - '--global.sendanonymoususage=${TRAEFIK_SEND_ANONYMOUS_USAGE:-false}'
      - '--ping=true'
    environment:
      - 'TZ=${TZ:-Europe/London}'
    # healthcheck:
    #   test: ['CMD-SHELL', 'traefik', 'healthcheck', '--ping']
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.rule: 'Host(`traefik.${DOMAIN_NAME:-localhost}`)'
      traefik.http.routers.traefik_https.entrypoints: websecure
      traefik.http.routers.traefik.service: 'api@internal'
      traefik.tls.stores.default.defaultgeneratedcert.resolver: myresolver
      traefik.tls.stores.default.defaultgeneratedcert.domain.main: localhost
      traefik.tls.stores.default.defaultgeneratedcert.domain.sans: whoami.localhost, traefik.localhost
    networks:
      - 'server'
    ports:
      - '${TRAEFIK_WEB_ENTRYPOINT:-80}:${TRAEFIK_WEB_ENTRYPOINT:-80}'
      - '${TRAEFIK_WEBSECURE_ENTRYPOINT:-443}:${TRAEFIK_WEBSECURE_ENTRYPOINT:-443}'
    restart: 'always'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './logs:/logs'